{{- if .Values.runScope.cluster -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "cre-common.labels" . | indent 4 }}

  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if (not .Values.useExistingRole) }}
  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
{{- else }}
  name: {{ .Values.useExistingRole }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-container-resource-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
