{{- if and .Values.runScope.cluster (not .Values.useExistingRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "cre-common.labels" . | indent 4 }}

  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - list
{{- end -}}
