apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-container-resource-exporter.name" . }}
    chart: {{ template "prometheus-container-resource-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "prometheus-container-resource-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "prometheus-container-resource-exporter.name" . }}
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: {{ template "prometheus-container-resource-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- if and .Values.runScope.local (not .Values.runScope.namespaces)  }}
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
{{- end }}
{{- if and .Values.runScope.local .Values.runScope.namespaces  }}
          env:
          - name: WATCH_NAMESPACE
            value: {{ join "," .Values.runScope.namespaces }}
{{- end }}
          ports:
            - containerPort: 9000
              name: server-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: server-port
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: server-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
