{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-container-resource-exporter.serviceAccountName" . }}
  labels:
{{ include "cre-common.labels" . | indent 4 }}

{{- end -}}
