apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "cre-common.labels" . | indent 4 }}
{{- with .Values.service.additionalLabels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
  name: {{ template "prometheus-container-resource-exporter.fullname" . }}
spec:
  ports:
  - name: server-port
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: server-port
  selector:
    app: {{ template "prometheus-container-resource-exporter.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}